## Comment out when doing local development
backend:
  name: github
  repo: atbcb/usab-uswds
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: master
  use_graphql: false

##
## Uncomment when doing local development on Netlify CMS
## Run `npx netlify-cms-proxy-server` to start working locally
## In another terminal, start the app with `npm start`
## See https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
##

# backend:
#   name: git-gateway
# local_backend: true

##
##

media_folder: images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: News
    name: posts
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {
        label: "Tags",
        name: "tags",
        widget: "relation",
        collection: "tags",
        searchFields: ["name"],
        valueField: "name",
        displayFields: ["name"],
        multiple: true,
      }
      - {label: "Show in Webinars", name: "webinar", widget: "boolean", default: false}
      - {
          required: false,
          label: "Webinar Date",
          name: "webinar-date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: true
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - label: Tags
    name: tags
    folder: _tags/
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    fields:
      - {
          label: "Name",
          name: "name",
          widget: "string",
          hint: 'The name of the tag',
        }
      - { label: "Description", name: "description", widget: "text", required: false }
