backend:
  name: github
  repo: atbcb/usab-uswds
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: master
  use_graphql: false

media_folder: images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: News
    name: posts
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          allow_add: false
        }
      - {label: "Show in Webinars", name: "webinar", widget: "boolean", default: false}
      - {
          required: false,
          label: "Webinar Date",
          name: "webinar-date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: true
        }
      - {label: "Body", name: "body", widget: "markdown"}
